name: Nextcloud
skillMetadata:
  sections:
    - name: Login
      fields:
        - type: label
          label: Nextcloud/CalDAV information
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
        - name: protocol
          type: select
          label: Protocol
          options: "HTTPS|https;HTTP|http"
          value: "https"
        - name: url
          type: text
          label: Server's url
          value: "example.com/nextcloud/remote.php/dav"
        - name: cache
          type: select
          label: Caching
          options: "No cache|false;1 hour|3600"
          value: "false"
        - name: checkInterval
          type: select
          label: Check for events and alerts
          options: "Never check|false;1 hour|3600"
          value: "false"
